# Generated by Django 5.0.6 on 2024-10-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='username',
            new_name='user',
        ),
    ]
